CREATE TABLE brukere (
  id INT AUTO_INCREMENT PRIMARY KEY,
  navn VARCHAR(100) NOT NULL,
  brukernavn VARCHAR(100) NOT NULL UNIQUE,
  passord_hash VARCHAR(255) NOT NULL,
  er_admin TINYINT(1) NOT NULL DEFAULT 0,
  aktiv TINYINT(1) NOT NULL DEFAULT 1,
  opprettet TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE varer (
  id INT AUTO_INCREMENT PRIMARY KEY,
  bruker_id INT NULL,
  lager_type ENUM('bil', 'felles') NOT NULL DEFAULT 'bil',
  navn VARCHAR(255) NOT NULL,
  elnummer VARCHAR(50) NOT NULL,
  antall INT NOT NULL DEFAULT 0,
  plassering VARCHAR(100),
  min_antall INT DEFAULT 1,
  oppdatert TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (bruker_id) REFERENCES brukere(id) ON DELETE CASCADE
);

CREATE TABLE lager_tilganger (
  id INT AUTO_INCREMENT PRIMARY KEY,
  bruker_id INT NOT NULL,
  eier_id INT NOT NULL,
  kan_lese TINYINT(1) NOT NULL DEFAULT 1,
  kan_redigere TINYINT(1) NOT NULL DEFAULT 0,
  UNIQUE KEY unik_tilgang (bruker_id, eier_id),
  FOREIGN KEY (bruker_id) REFERENCES brukere(id) ON DELETE CASCADE,
  FOREIGN KEY (eier_id) REFERENCES brukere(id) ON DELETE CASCADE
);
